name: hr_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  auto_route_generator: ^10.2.3
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.1.2
  gap: ^3.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  persistent_bottom_nav_bar: ^6.2.1
  animated_bottom_navigation_bar: ^1.4.0
  adaptive_dialog: ^2.4.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.0
  retrofit: ^4.6.0
  dio: ^5.8.0+1
  form_field_validator: ^1.1.0
  form_validator: ^2.1.1
  infinite_scroll_pagination: ^5.1.0
  skeletonizer: ^2.1.0+1
  dropdown_search: ^6.0.2
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  permission_handler: ^12.0.1
  location: ^8.0.1
  google_maps_flutter_android: ^2.17.0 
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.7.0
  build_runner: ^2.4.6 
  freezed: ^2.4.6
  json_serializable: ^6.9.5

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
